version: '2.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Rancher123
      - MYSQL_DATABASE=gogs
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
  gogs:
    image: gogs/gogs:latest
    restart: always
    links:
      - mysql:mysql
    depends_on:
      - mysql
    ports:
      - "2222:22"
      - 3000:3000
    volumes:
      - ./gogs/data:/data
